version: '3'

x-anchor:
  depends: &depends
    condition: service_completed_successfully
  service: &service
    entrypoint: sh -e -c
    network_mode: bridge
    volumes: [.:/mnt/repo]
    working_dir: /mnt/repo

services:
  typedoc:
    <<: *service
    image: node:latest
    command:
      - |
        cd $$(mktemp -d)
        git clone -b $SGRUD_TAG $SGRUD_GIT .
        npm pack /mnt/repo/res/typedoc-theme
        npm install *.tgz && npm install

        npx typedoc \
          --githubPages false \
          --gitRevision $SGRUD_TAG \
          --plugin typedoc-plugin-markdown \
          --plugin typedoc-plugin-mdn-links \
          --plugin @sgrud/typedoc-plugin \
          --plugin @sgrud/typedoc-theme \
          --out /mnt/repo/dist

  jest:
    <<: *service
    depends_on: {typedoc: *depends}
    image: node:latest
    command:
      - |
        cd $$(mktemp -d)
        git clone -b $SGRUD_TAG $SGRUD_GIT .
        npm install && npm run build

        npx jest --coverage --testPathIgnorePatterns /worker/ | sed -E \
          -e 's/^  /\\hspace{5mm}/g' -e 's/^ /\\hspace{2.5mm}/g' \
          -e '1s/.*/\n\\newpage\n\n# Test Coverage\n/;$$d' \
        >>/mnt/repo/dist/typedoc.md

  citation-js:
    <<: *service
    depends_on: {jest: *depends}
    image: node:latest
    command:
      - |
        cd $$(mktemp -d)
        npm pack /mnt/repo/res/bibtex-identifier
        npm install *.tgz && npm install

        npx citation-js \
          --plugins bibtex-identifier \
          --input /mnt/repo/CITATION.cff \
          --output /mnt/repo/dist/literature \
          --output-style bibtex \
          --output-type string

  pandoc:
    <<: *service
    build: res/pandoc-custom
    depends_on: {citation-js: *depends}
    image: pandoc/custom:latest
    command:
      - |
        FILES=$$(find src -name '*.md' | sort)

        pandoc -d pandoc.typedoc.yml dist/typedoc.md
        pandoc -d pandoc.thesis.yml -o dist/thesis.tex $$FILES
        xelatex -no-pdf -output-directory dist dist/thesis.tex
        xelatex -no-pdf -output-directory dist dist/thesis.tex
        makeindex -i -l -r <dist/thesis.idx >>dist/typedoc.tex
        pandoc -d pandoc.thesis.yml -o dist/thesis.pdf $$FILES
