name: SGRUD Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  thesis:
    name: Thesis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: ./source

      - name: Checkout target
        uses: actions/checkout@v3
        with:
          path: ./target
          repository: sgrud/sgrud.github.io
          ssh-key: ${{secrets.PAGES_DEPLOY_KEY}}

      - name: Build source
        working-directory: ./source
        run: |
          mkdir ./thesis
          docker compose up --no-log-prefix
          cp ./dist/thesis.pdf ./README.md ./thesis

      - name: Stage source
        working-directory: ./source
        run: |
          git --git-dir ../target/.git add -Af ./thesis

      - name: Push target
        working-directory: ./target
        run: |
          git diff --cached --quiet && exit
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -m ${{github.repository}}@${{github.sha}}
          git push
